import re

with open('/home/dinakar3108/Downloads/PR1/lib/services/i18n_service.dart', 'r', encoding='utf-8') as f:
    content = f.read()

pattern = r"'en': {"
start = content.find(pattern)
lines = content[start:].split('\n')
en_kv = {}
for line in lines:
    m = re.search(r"^\s*'([a-zA-Z0-9_]+)'\s*:\s*'(.*)'\s*,\s*$", line)
    if m:
        en_kv[m.group(1)] = m.group(2)
    if line.strip() == '},':
        break

print(f"Loaded {len(en_kv)} English keys.")

# Comprehensive word translation dictionary
vocab_ta = {
    'Active': 'செயலில் உள்ள',
    'Baseline': 'அடிப்படை நிலை',
    'Senior': 'மூத்த',
    'Cognitive': 'அறிவுத்திறன்',
    'Items': 'உருப்படிகள்',
    'Item': 'உருப்படி',
    'Medicine': 'மருந்து',
    'Medicines': 'மருந்துகள்',
    'Activities': 'நடவடிக்கைகள்',
    'Activity': 'நடவடிக்கை',
    'Instructions': 'அறிவுறுத்தல்கள்',
    'Instruction': 'அறிவுறுத்தல்',
    'Status': 'நிலை',
    'Header': 'தலைப்பு',
    'Title': 'தலைப்பு',
    'Subtitle': 'துணைத்தலைப்பு',
    'Description': 'விளக்கம்',
    'Details': 'விவரங்கள்',
    'Notes': 'குறிப்புகள்',
    'Note': 'குறிப்பு',
    'Card': 'அட்டை',
    'Cards': 'அட்டைகள்',
    'Pair': 'ஜோடி',
    'Pairs': 'ஜோடிகள்',
    'Match': 'பொருத்துக',
    'Matching': 'பொருத்துதல்',
    'Pattern': 'வடிவம்',
    'Patterns': 'வடிவங்கள்',
    'Sequence': 'வரிசை',
    'Sequences': 'வரிசைகள்',
    'Sorting': 'வரிசைப்படுத்துதல்',
    'Sort': 'வரிசைப்படுத்து',
    'Recall': 'நினைவுகூர்தல்',
    'Reflection': 'பிரதிபலிப்பு',
    'Reflect': 'பிரதிபலிப்பதாக',
    'Memory': 'நினைவகம்',
    'Memories': 'நினைவுகள்',
    'Story': 'கதை',
    'Stories': 'கதைகள்',
    'Voice': 'குரல்',
    'Audio': 'ஒலிப்பதிவு',
    'Video': 'காணொளி',
    'Photo': 'புகைப்படம்',
    'Photos': 'புகைப்படங்கள்',
    'Landmark': 'அடையாளச் சின்னம்',
    'Landmarks': 'அடையாளச் சின்னங்கள்',
    'Heritage': 'பாரம்பரியம்',
    'Cultural': 'கலாச்சார',
    'Symbol': 'சின்னம்',
    'Symbols': 'சின்னங்கள்',
    'Game': 'விளையாட்டு',
    'Games': 'விளையாட்டுகள்',
    'Score': 'மதிப்பெண்',
    'Scores': 'மதிப்பெண்கள்',
    'Level': 'நிலை',
    'Levels': 'நிலைகள்',
    'Accuracy': 'துல்லியம்',
    'Rate': 'விகிதம்',
    'Percentage': 'சதவீதம்',
    'Adherence': 'பின்பற்றுதல்',
    'Hydration': 'நீரேற்றம்',
    'Water': 'தண்ணீர்',
    'Glass': 'கிளாஸ்',
    'Glasses': 'கிளாஸ்கள்',
    'Liter': 'லிட்டர்',
    'Liters': 'லிட்டர்கள்',
    'Target': 'இலக்கு',
    'Goal': 'இலக்கு',
    'Pill': 'மாத்திரை',
    'Pills': 'மாத்திரைகள்',
    'Dose': 'அளவு',
    'Dosage': 'மருந்து அளவு',
    'Routine': 'நடைமுறை',
    'Routines': 'நடைமுறைகள்',
    'Reminder': 'நினைவூட்டல்',
    'Reminders': 'நினைவூட்டல்கள்',
    'Alarm': 'அலாரம்',
    'Alarms': 'அலாரங்கள்',
    'Notification': 'அறிவிப்பு',
    'Notifications': 'அறிவிப்புகள்',
    'Alert': 'எச்சரிக்கை',
    'Alerts': 'எச்சரிக்கைகள்',
    'Doctor': 'மருத்துவர்',
    'Hospital': 'மருத்துவமனை',
    'Appointment': 'சந்திப்பு',
    'Appointments': 'சந்திப்புகள்',
    'Caregiver': 'பராமரிப்பாளர்',
    'Elder': 'முதியவர்',
    'Patient': 'நோயாளி',
    'Worker': 'பணியாளர்',
    'Dashboard': 'டாஷ்போர்டு',
    'Overview': 'பார்வை',
    'Profile': 'சுயவிவரம்',
    'Settings': 'அமைப்புகள்',
    'Account': 'கணக்கு',
    'User': 'பயனர்',
    'Role': 'பங்கு',
    'Code': 'குறியீடு',
    'ID': 'அடையாள எண்',
    'Registration': 'பதிவு',
    'Login': 'உள்நுழைவு',
    'Register': 'பதிவு செய்',
    'Sign In': 'உள்நுழை',
    'Sign Out': 'வெளியேறு',
    'Log Out': 'வெளியேறு',
    'Password': 'கடவுச்சொல்',
    'Email': 'மின்னஞ்சல்',
    'Phone': 'தொலைபேசி',
    'Location': 'இருப்பிடம்',
    'Region': 'பகுதி',
    'Language': 'மொழி',
    'State': 'மாநிலம்',
    'City': 'நகரம்',
    'Address': 'முகவரி',
    'Name': 'பெயர்',
    'Age': 'வயது',
    'Gender': 'பாலினம்',
    'Male': 'ஆண்',
    'Female': 'பெண்',
    'Save': 'சேமி',
    'Delete': 'நீக்கு',
    'Cancel': 'ரத்து செய்',
    'Edit': 'திருத்து',
    'Update': 'புதுப்பி',
    'Clear': 'அழி',
    'Remove': 'அகற்று',
    'Add': 'சேர்',
    'Create': 'உருவாக்கு',
    'Submit': 'சமர்ப்பி',
    'Confirm': 'உறுதிப்படுத்து',
    'Verify': 'சரிபார்க்கவும்',
    'Verified': 'சரிபார்க்கப்பட்டது',
    'Search': 'தேடுக',
    'Filter': 'வடிகட்டி',
    'Select': 'தேர்ந்தெடு',
    'Choose': 'தேர்ந்தெடு',
    'Pick': 'தேர்ந்தெடு',
    'Upload': 'பதிவேற்று',
    'Record': 'பதிவுசெய்',
    'Play': 'இயக்கு',
    'Stop': 'நிறுத்து',
    'Pause': 'நிறுத்து',
    'Resume': 'தொடர்',
    'Next': 'அடுத்து',
    'Back': 'பின்னால்',
    'Close': 'மூடு',
    'Dismiss': 'தள்ளுபடி செய்',
    'OK': 'சரி',
    'Yes': 'ஆம்',
    'No': 'இல்லை',
    'All': 'அனைத்தும்',
    'None': 'எதுவுமில்லை',
    'Required': 'தேவையான',
    'Optional': 'விருப்பத்திற்குரிய',
    'Success': 'வெற்றி',
    'Error': 'பிழை',
    'Warning': 'எச்சரிக்கை',
    'Info': 'தகவல்',
    'Help': 'உதவி',
    'Support': 'ஆதரவு',
    'About': 'பற்றி',
    'Version': 'பதிப்பு',
    'Emergency': 'அவசரம்',
    'SOS': 'SOS',
    'Risk': 'அபாயம்',
    'Low': 'குறைந்த',
    'Moderate': 'மிதமான',
    'High': 'அதிக',
    'Great': 'சிறந்த',
    'Good': 'நல்ல',
    'Well': 'நன்றாக',
    'Practice': 'பயிற்சி',
    'Together': 'ஒன்றாக',
    'Extra': 'கூடுதல்',
    'Support': 'ஆதரவு',
    'Today': 'இன்று',
    'Yesterday': 'நேற்று',
    'Tomorrow': 'நாளை',
    'Morning': 'காலை',
    'Afternoon': 'மதியம்',
    'Evening': 'மாலை',
    'Night': 'இரவு',
    'Complete': 'முடிக்கவும்',
    'Completed': 'முடிந்தது',
    'Pending': 'நிலுவையில் உள்ளது',
    'Failed': 'தோல்வியுற்றது',
    'Passed': 'தேர்ச்சி பெற்றது',
    'Total': 'மொத்தம்',
    'Average': 'சராசரி',
    'Max': 'அதிகபட்சம்',
    'Min': 'குறைந்தபட்சம்',
}

vocab_ne = {
    'Active': 'सक्रिय',
    'Baseline': 'आधार रेखा',
    'Senior': 'ज्येष्ठ',
    'Cognitive': 'ज्ञानात्मक',
    'Items': 'वस्तुहरू',
    'Item': 'वस्तु',
    'Medicine': 'औषधि',
    'Medicines': 'औषधिहरू',
    'Activities': 'गतिविधिहरू',
    'Activity': 'गतिविधि',
    'Instructions': 'निर्देशनहरू',
    'Instruction': 'निर्देशन',
    'Status': 'स्थिति',
    'Header': 'शीर्षक',
    'Title': 'शीर्षक',
    'Subtitle': 'उपशीर्षक',
    'Description': 'विवरण',
    'Details': 'विवरणहरू',
    'Notes': 'नोटहरू',
    'Note': 'नोट',
    'Card': 'कार्ड',
    'Cards': 'कार्डहरू',
    'Pair': 'जोडी',
    'Pairs': 'जोडीहरू',
    'Match': 'मिलाउनुहोस्',
    'Matching': 'जोडा मिलाउने',
    'Pattern': 'ढाँचा',
    'Patterns': 'ढाँचाहरू',
    'Sequence': 'अनुक्रम',
    'Sequences': 'अनुक्रमहरू',
    'Sorting': 'क्रमबद्धता',
    'Sort': 'क्रमबद्ध गर्नुहोस्',
    'Recall': 'याद गर्नुहोस्',
    'Reflection': 'प्रतिबिम्ब',
    'Reflect': 'मनन गर्नुहोस्',
    'Memory': 'स्मृति',
    'Memories': 'यादहरू',
    'Story': 'कथा',
    'Stories': 'कथाहरू',
    'Voice': 'आवाज',
    'Audio': 'अडियो',
    'Video': 'भिडियो',
    'Photo': 'तस्बिर',
    'Photos': 'तस्बिरहरू',
    'Landmark': 'स्थल',
    'Landmarks': 'स्थलहरू',
    'Heritage': 'सम्पदा',
    'Cultural': 'सांस्कृतिक',
    'Symbol': 'प्रतीक',
    'Symbols': 'प्रतीकहरू',
    'Game': 'खेल',
    'Games': 'खेलहरू',
    'Score': 'अङ्क',
    'Scores': 'अङ्कहरू',
    'Level': 'स्तर',
    'Levels': 'स्तरहरू',
    'Accuracy': 'सटीकता',
    'Rate': 'दर',
    'Percentage': 'प्रतिशत',
    'Adherence': 'पालना',
    'Hydration': 'जलसञ्चार',
    'Water': 'पानी',
    'Glass': 'ग्लास',
    'Glasses': 'ग्लासहरू',
    'Liter': 'लिटर',
    'Liters': 'लिटर',
    'Target': 'लक्ष्य',
    'Goal': 'लक्ष्य',
    'Pill': 'ट्याब्लेट',
    'Pills': 'ट्याब्लेटहरू',
    'Dose': 'मात्रा',
    'Dosage': 'औषधि मात्रा',
    'Routine': 'दिनचर्या',
    'Routines': 'दिनचर्याहरू',
    'Reminder': 'सम्झौटो',
    'Reminders': 'सम्झौटोहरू',
    'Alarm': 'अलार्म',
    'Alarms': 'अलार्महरू',
    'Notification': 'सूचना',
    'Notifications': 'सूचनाहरू',
    'Alert': 'चेतावनी',
    'Alerts': 'चेतावनीहरू',
    'Doctor': 'डाक्टर',
    'Hospital': 'अस्पताल',
    'Appointment': 'भेटघाट',
    'Appointments': 'भेटघाटहरू',
    'Caregiver': 'हेरचाहकर्ता',
    'Elder': 'ज्येष्ठ नागरिक',
    'Patient': 'बिरामी',
    'Worker': 'कर्मचारी',
    'Dashboard': 'ड्यासबोर्ड',
    'Overview': 'अवलोकन',
    'Profile': 'प्रोफाइल',
    'Settings': 'सेटिङहरू',
    'Account': 'खाता',
    'User': 'प्रयोगकर्ता',
    'Role': 'भूमिका',
    'Code': 'कोड',
    'ID': 'आईडी',
    'Registration': 'दर्ता',
    'Login': 'लगइन गर्नुहोस्',
    'Register': 'दर्ता गर्नुहोस्',
    'Sign In': 'लगइन गर्नुहोस्',
    'Sign Out': 'लगआउट गर्नुहोस्',
    'Log Out': 'लगआउट गर्नुहोस्',
    'Password': 'पासवर्ड',
    'Email': 'इमेल',
    'Phone': 'फोन',
    'Location': 'स्थान',
    'Region': 'क्षेत्र',
    'Language': 'भाषा',
    'State': 'राज्य',
    'City': 'शहर',
    'Address': 'ठेगाना',
    'Name': 'नाम',
    'Age': 'उमेर',
    'Gender': 'लिङ्ग',
    'Male': 'पुरुष',
    'Female': 'महिला',
    'Save': 'बचत गर्नुहोस्',
    'Delete': 'हटाउनुहोस्',
    'Cancel': 'रद्द गर्नुहोस्',
    'Edit': 'सम्पादन गर्नुहोस्',
    'Update': 'अद्यावधिक गर्नुहोस्',
    'Clear': 'सफा गर्नुहोस्',
    'Remove': 'हटाउनुहोस्',
    'Add': 'थप्नुहोस्',
    'Create': 'सिर्जना गर्नुहोस्',
    'Submit': 'बुझाउनुहोस्',
    'Confirm': 'पुष्टि गर्नुहोस्',
    'Verify': 'प्रमाणित गर्नुहोस्',
    'Verified': 'प्रमाणित गरियो',
    'Search': 'खोज्नुहोस्',
    'Filter': 'फिल्टर',
    'Select': 'छान्नुहोस्',
    'Choose': 'छान्नुहोस्',
    'Pick': 'छान्नुहोस्',
    'Upload': 'अपलोड गर्नुहोस्',
    'Record': 'रेकर्ड गर्नुहोस्',
    'Play': 'प्ले गर्नुहोस्',
    'Stop': 'रोक्नुहोस्',
    'Pause': 'रोक्नुहोस्',
    'Resume': 'पुनः शुरू गर्नुहोस्',
    'Next': 'अर्को',
    'Back': 'पछाडि',
    'Close': 'बन्द गर्नुहोस्',
    'Dismiss': 'खारिज गर्नुहोस्',
    'OK': 'ठीक छ',
    'Yes': 'हो',
    'No': 'होइन',
    'All': 'सबै',
    'None': 'कुनै पनि छैन',
    'Required': 'आवश्यक',
    'Optional': 'ऐच्छिक',
    'Success': 'सफलता',
    'Error': 'त्रुटि',
    'Warning': 'चेतावनी',
    'Info': 'जानकारी',
    'Help': 'सहायता',
    'Support': 'सहयोग',
    'About': 'बारेमा',
    'Version': 'संस्करण',
    'Emergency': 'आपतकालीन',
    'SOS': 'SOS',
    'Risk': 'जोखिम',
    'Low': 'कम',
    'Moderate': 'मध्यम',
    'High': 'उच्च',
    'Great': 'उत्कृष्ट',
    'Good': 'राम्रो',
    'Well': 'राम्ररी',
    'Practice': 'अभ्यास',
    'Together': 'सँगै',
    'Extra': 'अतिरिक्त',
    'Support': 'सहयोग',
    'Today': 'आज',
    'Yesterday': 'हिजो',
    'Tomorrow': 'भोलि',
    'Morning': 'बिहान',
    'Afternoon': 'दिउँसो',
    'Evening': 'साँझ',
    'Night': 'राति',
    'Complete': 'पूरा गर्नुहोस्',
    'Completed': 'सम्पन्न भयो',
    'Pending': 'बाँकी छ',
    'Failed': 'असफल भयो',
    'Passed': 'उत्तीर्ण भयो',
    'Total': 'कुल',
    'Average': 'औसत',
    'Max': 'अधिकतम',
    'Min': 'न्यूनतम',
}

def translate_sentence_clean(en_text, vocab):
    res = en_text
    sorted_words = sorted(vocab.keys(), key=lambda x: len(x), reverse=True)
    for w in sorted_words:
        target = vocab[w]
        res = re.sub(r'\b' + re.escape(w) + r'\b', target, res, flags=re.IGNORECASE)
    return res

ta_clean = {}
ne_clean = {}

for k, en_val in en_kv.items():
    ta_clean[k] = translate_sentence_clean(en_val, vocab_ta)
    ne_clean[k] = translate_sentence_clean(en_val, vocab_ne)

print("Comprehensive translation map created.")
