import re
import sys

with open('/home/dinakar3108/Downloads/PR1/lib/services/i18n_service.dart', 'r', encoding='utf-8') as f:
    content = f.read()

# Extract 'en' keys
pattern = r"'en': {"
start = content.find(pattern)
lines = content[start:].split('\n')
en_kv = {}
for line in lines:
    m = re.search(r"^\s*'([a-zA-Z0-9_]+)'\s*:\s*'(.*)'\s*,\s*$", line)
    if m:
        en_kv[m.group(1)] = m.group(2)
    if line.strip() == '},':
        break

print(f"Loaded {len(en_kv)} English keys.")

# Dictionary of word/phrase translations per language
translations_db = {
    'ta': {
        'Login': 'உள்நுழைவு',
        'Create Account': 'கணக்கை உருவாக்கவும்',
        'Doctor Name': 'மருத்துவர் பெயர்',
        'Voice Note': 'குரல் பதிவு குறிப்பு',
        'Water Goal': 'நீர் இலக்கு',
        'Completed': 'முடிந்தது',
        'Pending': 'நிலுவையில் உள்ளது',
        'Save': 'சேமி',
        'Delete': 'நீக்கு',
        'Cancel': 'ரத்து செய்',
        'Add': 'சேர்',
        'Medicine': 'மருந்து',
        'Appointment': 'சந்திப்பு',
        'Activity': 'நடவடிக்கை',
        'Elder': 'முதியவர்',
        'Caretaker': 'பராமரிப்பாளர்',
        'Audio': 'ஒலிப்பதிவு',
        'Video': 'காணொளி',
        'Photo': 'புகைப்படம்',
        'Select': 'தேர்ந்தெடு',
        'Submit': 'சமர்ப்பி',
        'Next': 'அடுத்து',
        'Back': 'பின்னால்',
        'Confirm': 'உறுதிப்படுத்து',
        'Close': 'மூடு',
        'Time': 'நேரம்',
        'Date': 'தேதி',
        'Name': 'பெயர்',
        'Age': 'வயது',
        'Phone': 'தொலைபேசி',
        'Email': 'மின்னஞ்சல்',
        'Password': 'கடவுச்சொல்',
        'Role': 'பங்கு',
        'Location': 'இருப்பிடம்',
        'Region': 'பகுதி',
        'Language': 'மொழி',
        'Code': 'குறியீடு',
        'Registration': 'பதிவு',
        'Hydration': 'நீரேற்றம்',
        'Glasses': 'கிளாஸ்கள்',
        'Liters': 'லிட்டர்கள்',
        'Instructions': 'அறிவுறுத்தல்கள்',
        'Pill': 'மாத்திரை',
        'Pills': 'மாத்திரைகள்',
        'Routine': 'வரிசைமுறை',
        'Exercise': 'பயிற்சி',
        'Exercises': 'பயிற்சிகள்',
        'Memory': 'நினைவகம்',
        'Recall': 'நினைவு கூர்தல்',
        'Matching': 'பொருத்துதல்',
        'Pattern': 'வடிவம்',
        'Sorting': 'வரிசைப்படுத்துதல்',
        'Reflection': 'பிரதிபலிப்பு',
        'Story': 'கதை',
        'Games': 'விளையாட்டுகள்',
        'Game': 'விளையாட்டு',
        'Score': 'மதிப்பெண்',
        'Level': 'நிலை',
        'Accuracy': 'துல்லியம்',
        'Badge': 'பேட்ஜ்',
        'Dashboard': 'டாஷ்போர்டு',
        'Overview': 'பார்வை',
        'Settings': 'அமைப்புகள்',
        'Profile': 'சுயவிவரம்',
        'Notifications': 'அறிவிப்புகள்',
        'Emergency': 'அவசரம்',
        'Alert': 'எச்சரிக்கை',
        'Success': 'வெற்றி',
        'Error': 'பிழை',
        'Warning': 'எச்சரிக்கை',
        'Information': 'தகவல்',
        'Description': 'விளக்கம்',
        'Details': 'விவரங்கள்',
        'Status': 'நிலை',
        'Filter': 'வடிகட்டி',
        'All': 'அனைத்தும்',
        'None': 'எதுவுமில்லை',
    },
    'ne': {
        'Login': 'लगइन गर्नुहोस्',
        'Create Account': 'नयाँ खाता बनाउनुहोस्',
        'Doctor Name': 'डाक्टरको नाम',
        'Voice Note': 'आवाज नोट',
        'Water Goal': 'पानीको लक्ष्य',
        'Completed': 'सम्पन्न भयो',
        'Pending': 'बाँकी छ',
        'Save': 'बचत गर्नुहोस्',
        'Delete': 'हटाउनुहोस्',
        'Cancel': 'रद्द गर्नुहोस्',
        'Add': 'थप्नुहोस्',
        'Medicine': 'औषधि',
        'Appointment': 'भेटघाट',
        'Activity': 'गतिविधि',
        'Elder': 'ज्येष्ठ नागरिक',
        'Caretaker': 'हेरचाहकर्ता',
        'Audio': 'अडियो',
        'Video': 'भिडियो',
        'Photo': 'तस्बिर',
        'Select': 'छान्नुहोस्',
        'Submit': 'बुझाउनुहोस्',
        'Next': 'अर्को',
        'Back': 'पछाडि',
        'Confirm': 'पुष्टि गर्नुहोस्',
        'Close': 'बन्द गर्नुहोस्',
        'Time': 'समय',
        'Date': 'मिति',
        'Name': 'नाम',
        'Age': 'उमेर',
        'Phone': 'फोन',
        'Email': 'इमेल',
        'Password': 'पासवर्ड',
        'Role': 'भूमिका',
        'Location': 'स्थान',
        'Region': 'क्षेत्र',
        'Language': 'भाषा',
        'Code': 'कोड',
        'Registration': 'दर्ता',
        'Hydration': 'जलसञ्चार',
        'Glasses': 'ग्लासहरू',
        'Liters': 'लिटर',
        'Instructions': 'निर्देशनहरू',
        'Pill': 'ट्याब्लेट',
        'Pills': 'ट्याब्लेटहरू',
        'Routine': 'दिनचर्या',
        'Exercise': 'अभ्यास',
        'Exercises': 'अभ्यासहरू',
        'Memory': 'स्मृति',
        'Recall': 'याद गर्नुहोस्',
        'Matching': 'जोडा मिलाउने',
        'Pattern': 'ढाँचा',
        'Sorting': 'क्रमबद्धता',
        'Reflection': 'प्रतिबिम्ब',
        'Story': 'कथा',
        'Games': 'खेलहरू',
        'Game': 'खेल',
        'Score': 'अङ्क',
        'Level': 'स्तर',
        'Accuracy': 'सटीकता',
        'Badge': 'ब्याज',
        'Dashboard': 'ड्यासबोर्ड',
        'Overview': 'अवलोकन',
        'Settings': 'सेटिङहरू',
        'Profile': 'प्रोफाइल',
        'Notifications': 'सूचनाहरू',
        'Emergency': 'आपतकालीन',
        'Alert': 'सतर्कता',
        'Success': 'सफलता',
        'Error': 'त्रुटि',
        'Warning': 'चेतावनी',
        'Information': 'जानकारी',
        'Description': 'विवरण',
        'Details': 'विवरणहरू',
        'Status': 'स्थिति',
        'Filter': 'फिल्टर',
        'All': 'सबै',
        'None': 'कुनै पनि छैन',
    },
    'as': {
        'Login': 'লগ ইন কৰক',
        'Create Account': 'নতুন একাউণ্ট সৃষ্টি কৰক',
        'Doctor Name': 'চিকিৎসকৰ নাম',
        'Voice Note': 'ভয়েচ নোট',
        'Water Goal': 'পানী খোৱাৰ লক্ষ্য',
        'Completed': 'সম্পূৰ্ণ হ\'ল',
        'Pending': 'বাকী আছে',
        'Save': 'সংৰক্ষণ কৰক',
        'Delete': 'মচি পেলাওক',
        'Cancel': 'বাতিল কৰক',
        'Add': 'যোগ কৰক',
        'Medicine': 'ঔষধ',
        'Appointment': 'চিকিৎসা সাক্ষাত',
        'Activity': 'কাৰ্যসূচী',
        'Elder': 'জ্যেষ্ঠ ব্যক্তি',
        'Caretaker': 'পৰিচৰ্যাকাৰী',
        'Audio': 'অডিঅ\'',
        'Video': 'ভিডিঅ\'',
        'Photo': 'ফটো',
        'Select': 'বাছনি কৰক',
        'Submit': 'জমা দিয়ক',
        'Next': 'পৰৱৰ্তী',
        'Back': 'পিছলৈ',
        'Confirm': 'নিশ্চিত কৰক',
        'Close': 'বন্ধ কৰক',
        'Time': 'সময়',
        'Date': 'তাৰিখ',
        'Name': 'নাম',
        'Age': 'বয়স',
        'Phone': 'ফোন',
        'Email': 'ইমেইল',
        'Password': 'পাছৱৰ্ড',
        'Role': 'ভূমিকা',
        'Location': 'স্থান',
        'Region': 'অঞ্চল',
        'Language': 'ভাষা',
        'Code': 'ক’ড',
        'Registration': 'পঞ্জীয়ন',
        'Hydration': 'পানী খোৱা',
        'Glasses': 'গ্লাছ',
        'Liters': 'লিটাৰ',
        'Instructions': 'নিৰ্দেশনা',
        'Pill': 'বড়ি',
        'Pills': 'বড়ি',
        'Routine': 'নিয়মীয়া কাৰ্যসূচী',
        'Exercise': 'ব্যায়াম',
        'Exercises': 'ব্যায়ামসমূহ',
        'Memory': 'স্মৃতি',
        'Recall': 'মনত পেলোৱা',
        'Matching': 'মিল কৰা',
        'Pattern': 'আৰ্হি',
        'Sorting': 'ক্ৰমবদ্ধ কৰা',
        'Reflection': 'চিন্তন',
        'Story': 'সাধু/কাহিনী',
        'Games': 'খেলসমূহ',
        'Game': 'খেল',
        'Score': 'স্ক’ৰ',
        'Level': 'স্তৰ',
        'Accuracy': 'তাত্ত্বিক শুদ্ধতা',
        'Badge': 'বেজ',
        'Dashboard': 'ডেশ্ববৰ্ড',
        'Overview': 'পৰ্যালোচনা',
        'Settings': 'ছেটিংছ',
        'Profile': 'প্রফাইল',
        'Notifications': 'অধিসূচনা',
        'Emergency': 'জৰুৰীকালীন',
        'Alert': 'সতৰ্কবাৰ্তা',
        'Success': 'সফল',
        'Error': 'ত্ৰুটি',
        'Warning': 'সীয়ানী বাৰ্তা',
        'Information': 'তথ্য',
        'Description': 'বিৱৰণ',
        'Details': 'বিৱৰণসমূহ',
        'Status': 'স্থিতি',
        'Filter': 'ফিল্টাৰ',
        'All': 'সকলো',
        'None': 'একো নাই',
    },
    'bn': {
        'Login': 'লগ ইন করুন',
        'Create Account': 'নতুন অ্যাকাউন্ট তৈরি করুন',
        'Doctor Name': 'ডাক্তারের নাম',
        'Voice Note': 'ভয়েস নোট',
        'Water Goal': 'জল পানের লক্ষ্য',
        'Completed': 'সম্পন্ন হয়েছে',
        'Pending': 'বাকি আছে',
        'Save': 'সংরক্ষণ করুন',
        'Delete': 'মুছে ফেলুন',
        'Cancel': 'বাতিল করুন',
        'Add': 'যোগ করুন',
        'Medicine': 'ঔষধ',
        'Appointment': 'ডাক্তারের অ্যাপয়েন্টমেন্ট',
        'Activity': 'ক্রিয়াকলাপ',
        'Elder': 'প্রবীণ ব্যক্তি',
        'Caretaker': 'সেবিকা/যত্নশীল',
        'Audio': 'অডিও',
        'Video': 'ভিডিও',
        'Photo': 'ছবি',
        'Select': 'নির্বাচন করুন',
        'Submit': 'জমা দিন',
        'Next': 'পরবর্তী',
        'Back': 'পেছনে',
        'Confirm': 'নিশ্চিত করুন',
        'Close': 'বন্ধ করুন',
        'Time': 'সময়',
        'Date': 'তারিখ',
        'Name': 'নাম',
        'Age': 'বয়স',
        'Phone': 'ফোন',
        'Email': 'ইমেল',
        'Password': 'পাসওয়ার্ড',
        'Role': 'ভূমিকা',
        'Location': 'অবস্থান',
        'Region': 'অঞ্চল',
        'Language': 'ভাষা',
        'Code': 'কোড',
        'Registration': 'নিবন্ধন',
        'Hydration': 'জলপান',
        'Glasses': 'গ্লাস',
        'Liters': 'লিটার',
        'Instructions': 'নির্দেশাবলী',
        'Pill': 'ট্যাবলেট',
        'Pills': 'ট্যাবলেট',
        'Routine': 'রুটিন',
        'Exercise': 'ব্যায়াম',
        'Exercises': 'ব্যায়ামসমূহ',
        'Memory': 'স্মৃতি',
        'Recall': 'স্মরণ',
        'Matching': 'মিলানো',
        'Pattern': 'প্যাটার্ন',
        'Sorting': 'সাজানো',
        'Reflection': 'প্রতিফলন',
        'Story': 'গল্প',
        'Games': 'খেলাধুলা',
        'Game': 'খেলা',
        'Score': 'স্কোর',
        'Level': 'স্তর',
        'Accuracy': 'সঠিকতা',
        'Badge': 'ব্যাজ',
        'Dashboard': 'ড্যাশবোর্ড',
        'Overview': 'পর্যালোচনা',
        'Settings': 'সেটিংস',
        'Profile': 'প্রোফাইল',
        'Notifications': 'বিজ্ঞপ্তি',
        'Emergency': 'জরুরী',
        'Alert': 'সতর্কতা',
        'Success': 'সফল',
        'Error': 'ত্রুটি',
        'Warning': 'সতর্কবার্তা',
        'Information': 'তথ্য',
        'Description': 'বিবরণ',
        'Details': 'বিস্তারিত',
        'Status': 'অবস্থা',
        'Filter': 'ফিল্টার',
        'All': 'সব',
        'None': 'কিছুই নয়',
    },
    'mni': {
        'Login': 'লগ ইন তৌবা',
        'Create Account': 'অনৌবা একাউন্ট শেম্বা',
        'Doctor Name': 'লাইয়েংবগী মিং',
        'Voice Note': 'খোঞ্জেল নোট',
        'Water Goal': 'ঈশিং থকপগী পাান্দম',
        'Completed': 'লোইরে',
        'Pending': 'লোইদ্রি',
        'Save': 'শেভ তৌবা',
        'Delete': 'মুত্থোকপা',
        'Cancel': 'কাকথোকপা',
        'Add': 'হাপচিনবা',
        'Medicine': 'হিদাক',
        'Appointment': 'লাইয়েংবগা উনবগী থৌরাং',
        'Activity': 'থৌরাং',
        'Elder': 'অহল',
        'Caretaker': 'য়ুমথম্বা',
        'Audio': 'ওডিও',
        'Video': 'ভিডিও',
        'Photo': 'ফোতো',
        'Select': 'খনব',
        'Submit': 'পিশিনবা',
        'Next': 'মতুংগী',
        'Back': 'হন্না',
        'Confirm': 'চেক তৌবা / পিবা',
        'Close': 'লোইশিনবা',
        'Time': 'মতং',
        'Date': 'তাং',
        'Name': 'মিং',
        'Age': 'চাহি',
        'Phone': 'ফোন',
        'Email': 'ইমেল',
        'Password': 'পাসৱাৰ্ড',
        'Role': 'থৌদাং',
        'Location': 'মফম',
        'Region': 'লমদম',
        'Language': 'লোন',
        'Code': 'কোড',
        'Registration': 'রেজিষ্ট্রেশন',
        'Hydration': 'ঈশিং থকপা',
        'Glasses': 'গ্লাস',
        'Liters': 'লিটর',
        'Instructions': 'তাকপি-থম্বিরিবা',
        'Pill': 'হিদাক মরাুম',
        'Pills': 'হিদাক মরাুমশিং',
        'Routine': 'নুমিৎ খুদিংগী থৌরাং',
        'Exercise': 'এক্সারসাইজ',
        'Exercises': 'এক্সারসাইজশিং',
        'Memory': 'নিনিংশিং',
        'Recall': 'নিনিংশিংবা',
        'Matching': 'মান্নবা খনব',
        'Pattern': 'মশোক',
        'Sorting': 'কাংলুপ খাইবা',
        'Reflection': 'ৱাখল খনব',
        'Story': 'ৱারী',
        'Games': 'শান্নবশিং',
        'Game': 'শান্নবা',
        'Score': 'স্কোর',
        'Level': 'থাক',
        'Accuracy': 'চুমহানবা',
        'Badge': 'ব্যাজ',
        'Dashboard': 'ড্যাশবোর্ড',
        'Overview': 'য়েংশিনবা',
        'Settings': 'সেটিংস',
        'Profile': 'প্রোফাইল',
        'Notifications': 'পাউদোল',
        'Emergency': 'অতেনবা থৌদোক',
        'Alert': 'চেকশিনৱা',
        'Success': 'মাইবুমবা',
        'Error': 'অশুম্বা',
        'Warning': 'চেকশিন পাউদোল',
        'Information': 'পাউ',
        'Description': 'শন্দোক্না তাকপা',
        'Details': 'শন্দোক্না',
        'Status': 'ফিভম',
        'Filter': 'ফিল্টার',
        'All': 'পুম্নমক',
        'None': 'অমতসু নত্তে',
    },
    'lus': {
        'Login': 'Lut rawh',
        'Create Account': 'Account thar siam rawh',
        'Doctor Name': 'Daktawr hming',
        'Voice Note': 'Tawng aw chhinchhiahna',
        'Water Goal': 'Tui in tum zak',
        'Completed': 'Zo tawh',
        'Pending': 'La ti lo',
        'Save': 'Vawng tha rawh',
        'Delete': 'Nawhre rawng',
        'Cancel': 'Thulh rawh',
        'Add': 'Belh rawh',
        'Medicine': 'Damdawi',
        'Appointment': 'Daktawr inhmuhna',
        'Activity': 'Thiltih',
        'Elder': 'Upa',
        'Caretaker': 'Chawmhtu',
        'Audio': 'Audio',
        'Video': 'Video',
        'Photo': 'Thlalak',
        'Select': 'Thlang rawh',
        'Submit': 'Thawn rawh',
        'Next': 'A dawt',
        'Back': 'Kir rawh',
        'Confirm': 'Nemnghet rawh',
        'Close': 'Khar rawh',
        'Time': 'Massa / Hun',
        'Date': 'Ni chhiar',
        'Name': 'Hming',
        'Age': 'Kum',
        'Phone': 'Phone',
        'Email': 'Email',
        'Password': 'Password',
        'Role': 'Mawhphurhna',
        'Location': 'Hmun',
        'Region': 'Ram cheh',
        'Language': 'Tawng',
        'Code': 'Code',
        'Registration': 'Inziathluhna',
        'Hydration': 'Tui in zat',
        'Glasses': 'No',
        'Liters': 'Liter',
        'Instructions': 'Zirtirna',
        'Pill': 'Mura',
        'Pills': 'Mura te',
        'Routine': 'Nitin kalphung',
        'Exercise': 'Sahlam',
        'Exercises': 'Sahlam te',
        'Memory': 'Hriatreuna',
        'Recall': 'Hriat chhuah',
        'Matching': 'Zawn fawm',
        'Pattern': 'Entirna',
        'Sorting': 'Indawt siam',
        'Reflection': 'Ngaihtuahna',
        'Story': 'Thawnthu',
        'Games': 'Infiamna te',
        'Game': 'Infiamna',
        'Score': 'Mark',
        'Level': 'Chhoh dan',
        'Accuracy': 'Dik zong',
        'Badge': 'Chhinchhiahna',
        'Dashboard': 'Dashboard',
        'Overview': 'Inenlawkna',
        'Settings': 'Ruahmanna te',
        'Profile': 'Mahni chanchin',
        'Notifications': 'Hriattirna te',
        'Emergency': 'Thil thut',
        'Alert': 'Hnawmhne alert',
        'Success': 'Puitling',
        'Error': 'Diksual',
        'Warning': 'Vaukhanna',
        'Information': 'Hrechiang',
        'Description': 'Hrilhfiahna',
        'Details': 'Chanchin kimchang',
        'Status': 'Dinhmun',
        'Filter': 'Thlitfim',
        'All': 'A vaive in',
        'None': 'A engmah lo',
    },
    'kha': {
        'Login': 'Buh kyrteng / Login',
        'Create Account': 'Thaw account thymmai',
        'Doctor Name': 'Kyrteng Nongsumar',
        'Voice Note': 'Jingkynmaw Sur Syiem',
        'Water Goal': 'Jingthmu Um Dih',
        'Completed': 'Dep',
        'Pending': 'Sah',
        'Save': 'Kynshew',
        'Delete': 'Pynduh',
        'Cancel': 'Pynsangeh',
        'Add': 'Buh lang',
        'Medicine': 'Dawai',
        'Appointment': 'Jingiashem Bad Nongsumar',
        'Activity': 'Ki kam man ka sngi',
        'Elder': 'Ki Tymmen',
        'Caretaker': 'Jingsumar',
        'Audio': 'Audio',
        'Video': 'Video',
        'Photo': 'Dur',
        'Select': 'Jied',
        'Submit': 'Phah',
        'Next': 'Ba bud',
        'Back': 'Dien',
        'Confirm': 'Pynskhem',
        'Close': 'Khang',
        'Time': 'Por',
        'Date': 'Tarikh',
        'Name': 'Kyrteng',
        'Age': 'Rta',
        'Phone': 'Phone',
        'Email': 'Email',
        'Password': 'Password',
        'Role': 'Kyntien',
        'Location': 'Shnong / Hmun',
        'Region': 'Tylli',
        'Language': 'Ktien',
        'Code': 'Code',
        'Registration': 'Jingbuh kyrteng',
        'Hydration': 'Um dih',
        'Glasses': 'Klass',
        'Liters': 'Liter',
        'Instructions': 'Jingbthah',
        'Pill': 'Dawai kuli',
        'Pills': 'Dawai kuli',
        'Routine': 'Rukom lehkai',
        'Exercise': 'Jingpynkhlain',
        'Exercises': 'Ki kam pynkit jingmut',
        'Memory': 'Jingkynmaw',
        'Recall': 'Kynmaw biang',
        'Matching': 'Pyniasoh',
        'Pattern': 'Rukom',
        'Sorting': 'Pynbeit',
        'Reflection': 'Jingpyrkhat',
        'Story': 'Puriskam',
        'Games': 'Jinglehkai te',
        'Game': 'Jinglehkai',
        'Score': 'Mark',
        'Level': 'Kyrdan',
        'Accuracy': 'Jingbeit',
        'Badge': 'Dak',
        'Dashboard': 'Dashboard',
        'Overview': 'Jingkynmaw',
        'Settings': 'Jingpynbeit',
        'Profile': 'Profile',
        'Notifications': 'Jingpyntip',
        'Emergency': 'Jingkyndit',
        'Alert': 'Jingma',
        'Success': 'Jop',
        'Error': 'Bakla',
        'Warning': 'Jingmah',
        'Information': 'Jingtip',
        'Description': 'Jingbatai',
        'Details': 'Batai bniah',
        'Status': 'Long rta',
        'Filter': 'Jied bniah',
        'All': 'Baroh',
        'None': 'Lymda',
    },
    'nag': {
        'Login': 'Login kuribi',
        'Create Account': 'Naya account banabole',
        'Doctor Name': 'Doctor laga naam',
        'Voice Note': 'Awaaz note',
        'Water Goal': 'Paani khabo target',
        'Completed': 'Kuri loishe',
        'Pending': 'Bachi ase',
        'Save': 'Save kuribi',
        'Delete': 'Delete kuribi',
        'Cancel': 'Cancel kuribi',
        'Add': 'Add kuribi',
        'Medicine': 'Dawa',
        'Appointment': 'Doctor milibo time',
        'Activity': 'Kam',
        'Elder': 'Bura Manu',
        'Caretaker': 'Caregiver',
        'Audio': 'Audio',
        'Video': 'Video',
        'Photo': 'Photo',
        'Select': 'Select kuribi',
        'Submit': 'Submit kuribi',
        'Next': 'Aage laga',
        'Back': 'Piche',
        'Confirm': 'Confirm kuribi',
        'Close': 'Bandh kuribi',
        'Time': 'Time',
        'Date': 'Date',
        'Name': 'Naam',
        'Age': 'Ummer',
        'Phone': 'Phone',
        'Email': 'Email',
        'Password': 'Password',
        'Role': 'Role',
        'Location': 'Jagah',
        'Region': 'Area',
        'Language': 'Bhasa',
        'Code': 'Code',
        'Registration': 'Registration',
        'Hydration': 'Paani khabo',
        'Glasses': 'Glass',
        'Liters': 'Liter',
        'Instructions': 'Kene kuribo niyam',
        'Pill': 'Goli',
        'Pills': 'Goli khan',
        'Routine': 'Rojina niyam',
        'Exercise': 'Exercise',
        'Exercises': 'Exercise khan',
        'Memory': 'Yaad',
        'Recall': 'Yaad kuribo',
        'Matching': 'Milaikena dekhibo',
        'Pattern': 'Design',
        'Sorting': 'Sajabo',
        'Reflection': 'Sobi / Yaad',
        'Story': 'Kutha / Story',
        'Games': 'Khel khan',
        'Game': 'Khel',
        'Score': 'Score',
        'Level': 'Level',
        'Accuracy': 'Sahi takhat',
        'Badge': 'Badge',
        'Dashboard': 'Dashboard',
        'Overview': 'Dekhibo',
        'Settings': 'Settings',
        'Profile': 'Profile',
        'Notifications': 'Khobor',
        'Emergency': 'Zaroori',
        'Alert': 'Alert',
        'Success': 'Hoigoishe',
        'Error': 'Galti',
        'Warning': 'Warning',
        'Information': 'Jaankari',
        'Description': 'Bistar te',
        'Details': 'Sabji details',
        'Status': 'Halat',
        'Filter': 'Filter',
        'All': 'Sob',
        'None': 'Ekko nahaye',
    }
}

def translate_sentence(en_text, lang):
    # If text is exact match in db
    if en_text in translations_db[lang]:
        return translations_db[lang][en_text]
    
    # Replace individual terms if whole sentence contains placeholders or common words
    res = en_text
    for en_word, target_word in translations_db[lang].items():
        # Word boundary replace
        res = re.sub(r'\b' + re.escape(en_word) + r'\b', target_word, res, flags=re.IGNORECASE)
    
    return res

print("Built translation processor function.")

